/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc_transfer.h"

int *
open_rpc_1_svc(filename *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

void *
close_rpc_1_svc(int *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return (void *) &result;
}

data *
read_rpc_1_svc(int *argp, struct svc_req *rqstp)
{
	static data  result;

	/*
	 * insert server code here
	 */

	return &result;
}
