/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc_transfer.h"

bool_t
xdr_filename (XDR *xdrs, filename *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->filename_val, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_data (XDR *xdrs, data *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->data_val, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->data_len))
		 return FALSE;
	return TRUE;
}
