/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_TRANSFER_H_RPCGEN
#define _RPC_TRANSFER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct filename {
	char *filename_val;
};
typedef struct filename filename;

struct data {
	char *data_val;
	int data_len;
};
typedef struct data data;

#define FILE_TRANSFER_PROG 0x31230000
#define FILE_TRANSFER_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define OPEN_RPC 1
extern  int * open_rpc_1(filename *, CLIENT *);
extern  int * open_rpc_1_svc(filename *, struct svc_req *);
#define CLOSE_RPC 2
extern  void * close_rpc_1(int *, CLIENT *);
extern  void * close_rpc_1_svc(int *, struct svc_req *);
#define READ_RPC 3
extern  data * read_rpc_1(int *, CLIENT *);
extern  data * read_rpc_1_svc(int *, struct svc_req *);
extern int file_transfer_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define OPEN_RPC 1
extern  int * open_rpc_1();
extern  int * open_rpc_1_svc();
#define CLOSE_RPC 2
extern  void * close_rpc_1();
extern  void * close_rpc_1_svc();
#define READ_RPC 3
extern  data * read_rpc_1();
extern  data * read_rpc_1_svc();
extern int file_transfer_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_filename (XDR *, filename*);
extern  bool_t xdr_data (XDR *, data*);

#else /* K&R C */
extern bool_t xdr_filename ();
extern bool_t xdr_data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_TRANSFER_H_RPCGEN */
