/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TRANFER_H_RPCGEN
#define _TRANFER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define BUFFER_SIZE 1024

struct file_chunk {
	int size;
	char data[BUFFER_SIZE];
};
typedef struct file_chunk file_chunk;

#define FILE_TRANSFER 0x31234567
#define FILE_TRANSFER_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define send_file 1
extern  file_chunk * send_file_1(char **, CLIENT *);
extern  file_chunk * send_file_1_svc(char **, struct svc_req *);
extern int file_transfer_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define send_file 1
extern  file_chunk * send_file_1();
extern  file_chunk * send_file_1_svc();
extern int file_transfer_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_file_chunk (XDR *, file_chunk*);

#else /* K&R C */
extern bool_t xdr_file_chunk ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TRANFER_H_RPCGEN */
