/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "tranfer.h"

bool_t
xdr_file_chunk (XDR *xdrs, file_chunk *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->data, BUFFER_SIZE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
