/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc_transfer.h"


void
file_transfer_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	filename  open_rpc_1_arg;
	void  *result_2;
	int  close_rpc_1_arg;
	data  *result_3;
	int  read_rpc_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, FILE_TRANSFER_PROG, FILE_TRANSFER_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = open_rpc_1(&open_rpc_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = close_rpc_1(&close_rpc_1_arg, clnt);
	if (result_2 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = read_rpc_1(&read_rpc_1_arg, clnt);
	if (result_3 == (data *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	file_transfer_prog_1 (host);
exit (0);
}
